Repository IATI/IATI-Websites, pull requests merged in 2018-07, with the labels that each got.

#200 Fix path to sidemenu icons
  iatistandard/_static/library/js/iati.js
Labels: complete

#201 live <- master
  iatistandard/_static/library/js/iati.js
Labels: complete

#202 Add redirects for new guidance content of new website
  iatistandard/2018-redirects.conf
  iatistandard/redirects.conf
Labels: complete, enhancement

#204 Merge master in to live
  deployment/deploy_iati_standard.sh
  iatistandard/2018-redirects.conf
  iatistandard/redirects.conf
  salt-config/roster
  salt/authorized_keys
  salt/base.sls
Labels: complete, enhancement

#205 Update incorrect redirect links
  iatistandard/2018-redirects.conf
Labels: complete, enhancement

#206 Merge master into live
  iatistandard/2018-redirects.conf
Labels: complete, enhancement

#207 Update redirect typo
  iatistandard/2018-redirects.conf
Labels: bug, complete

#208 Merge master into live
  iatistandard/2018-redirects.conf
Labels: bug, complete
